name: plugin_translations
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  plugin:
    platforms:
      android:
        package: com.example.plugin_translations
        pluginClass: PluginTranslationsPlugin
      ios:
        pluginClass: PluginTranslationsPlugin